/*
Candlepin

Testing CloudRegistrationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	openapiclient "github.com/joshmalbrecht/candlepin-go-client/pkg"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_openapi_CloudRegistrationAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CloudRegistrationAPIService CancelCloudAccountJobs", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var cloudAccountId string

		resp, httpRes, err := apiClient.CloudRegistrationAPI.CancelCloudAccountJobs(context.Background(), cloudAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudRegistrationAPIService CloudAuthorize", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.CloudRegistrationAPI.CloudAuthorize(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CloudRegistrationAPIService DeleteAnonymousConsumersByAccountId", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.CloudRegistrationAPI.DeleteAnonymousConsumersByAccountId(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
