/*
Candlepin

Candlepin is a subscription management server written in Java. It helps with management of software subscriptions.

API version: 4.4.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NestedEntitlementDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NestedEntitlementDTO{}

// NestedEntitlementDTO struct for NestedEntitlementDTO
type NestedEntitlementDTO struct {
	Id *string `json:"id,omitempty"`
	Href *string `json:"href,omitempty"`
}

// NewNestedEntitlementDTO instantiates a new NestedEntitlementDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedEntitlementDTO() *NestedEntitlementDTO {
	this := NestedEntitlementDTO{}
	return &this
}

// NewNestedEntitlementDTOWithDefaults instantiates a new NestedEntitlementDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedEntitlementDTOWithDefaults() *NestedEntitlementDTO {
	this := NestedEntitlementDTO{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NestedEntitlementDTO) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedEntitlementDTO) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NestedEntitlementDTO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NestedEntitlementDTO) SetId(v string) {
	o.Id = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *NestedEntitlementDTO) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedEntitlementDTO) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *NestedEntitlementDTO) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *NestedEntitlementDTO) SetHref(v string) {
	o.Href = &v
}

func (o NestedEntitlementDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NestedEntitlementDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	return toSerialize, nil
}

type NullableNestedEntitlementDTO struct {
	value *NestedEntitlementDTO
	isSet bool
}

func (v NullableNestedEntitlementDTO) Get() *NestedEntitlementDTO {
	return v.value
}

func (v *NullableNestedEntitlementDTO) Set(val *NestedEntitlementDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedEntitlementDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedEntitlementDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedEntitlementDTO(val *NestedEntitlementDTO) *NullableNestedEntitlementDTO {
	return &NullableNestedEntitlementDTO{value: val, isSet: true}
}

func (v NullableNestedEntitlementDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedEntitlementDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


